 let projectChunks = [
    { link:"https://alikurtulush.dev/SEI-Pacman/",
      github:"https://github.com/kopanarya/SEI-Pacman",
      category:"gaming",
      imgUrl:"images/pacman/pacman-screen.png",
      projectTitle:"Pacman",
      imgFolder:"pacman",
      projectImagesArr:["pacman-screen.png","pacman-second.png","pacman-third.png"],
      description:"I recreated Pacman using Vanilla JavaScript for the movement of the characters. I used HTML5 and CSS3 to build and design the game.",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png"]
    },
    { link:"https://alikurtulush.dev/Project-2",
      github:"https://github.com/kopanarya/Project-2",
      category:"other",
      imgUrl:"images/londondaily/londondaily-screen.png",
      projectTitle:"DailyApp",
      imgFolder:"londondaily",
      projectImagesArr:["londondaily-screen.png","londondaily-second.png","londondaily-third.png"],
      description:"Our project was about London daily news. With this project, we tried to keep Londoners informed on various topics: tube status,weather, bike points, airquality.",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","react-icon.png","api-icon.png","webpack-icon.png","yarnpkg-icon.png"]
    },
    { link:"https://gaeventup.herokuapp.com/#/",
      github:"https://github.com/kopanarya/eventsUp",
      category:"fullStack",
      imgUrl:"images/eventup/eventup-screen.png",
      projectTitle:"EventUp",
      imgFolder:"eventup",
      projectImagesArr:["eventup-screen.png","eventup-second.png","eventup-third.png","eventup-fourth.png"],
      description:"We created a full-stack music application. Features include searching for a venue or gig, adding a new event or providing comments on their experience. ",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","api-icon.png","mongodb-icon.png","nodejs-icon.png","npm-icon.png","sass-icon.png","react-icon.png"]
    },
    { link:"https://travelonar.herokuapp.com/#/",
      github:"https://github.com/kopanarya/Travelonar",
      category:"fullStack",
      imgUrl:"images/travelonar/travelonar-screen.png",
      projectTitle:"Travelonar",
      imgFolder:"travelonar",
      projectImagesArr:["travelonar-screen.png","travelonar-second.png","travelonar-third.png","travelonar-fourth.png","travelonar-fifth.png","travelonar-sixth.png","travelonar-seventh.png"],
      description:"My project was a city guide for the traveller. User can type a city name and get pieces of information about news, restaurants, events, landmarks, stories, nightlife.",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","python-icon.png","react-icon.png","postgresql-icon.png","api-icon.png"]
    },
    { link:"https://5f32d65d1d8cb5c457cc22f3--quizzical-goldstine-594e6d.netlify.app/",
      github:"https://github.com/kopanarya/SocketIOChat",
      category:"other",
      imgUrl:"images/socketio/chat-screen.png",
      projectTitle:"SocketIOChat",
      imgFolder:"socketio",
      projectImagesArr:["chat-screen.png","chat-second.png","chat-third.png"],
      description:"My project is a chat live chat program. You can chat your friend easily and privately. ",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","react-icon.png","api-icon.png","nodejs-icon.png","npm-icon.png","socketio-icon.png"]
    },
    { link:"https://alikurtulush.dev/HangmanApp/",
      github:"https://github.com/kopanarya/HangmanApp",
      category:"gaming",
      imgUrl:"images/hangman/hangman-second.png",
      projectTitle:"HangmanApp",
      imgFolder:"hangman",
      projectImagesArr:["hangman-second.png","hangman-screen.png","hangman-third.png"],
      description:"I recreated hangman with pure vanilla.JS. ",
      usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png"]
  },
  {  link:"https://alikurtulush.dev/VueJSQuiz/",
     github:"https://github.com/kopanarya/VueJSQuiz",
     category:"gaming",
     imgUrl:"images/vuequiz/vuequiz-screen.png",
     projectTitle:"VueJSQuiz",
     imgFolder:"vuequiz",
     projectImagesArr:["vuequiz-screen.png","vuequiz-second.png","vuequiz-third.png"],
     description:"I built quiz app for quiz lover with Vue.js",
     usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","vue-icon.png","api-icon.png"]
  },
  {
    link:"http://alikurtulush.dev/VueJSTodo/",
    github:"https://github.com/kopanarya/VueJSTodo",
    category:"other",
    imgUrl:"images/vuejstodo/vuetodo-screen.png",
    projectTitle:"VueJSTodo",
    imgFolder:"vuejstodo",
    projectImagesArr:["vuetodo-screen.png","vuetodo-second.png","vuetodo-third.png"],
    description:"I built todo app for for planner   with Vue.js",
    usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","vue-icon.png"]
  },
  {
    link:"http://alikurtulush.dev/DadJokesApp/",
    github:"https://github.com/kopanarya/DadJokesApp",
    category:"other",
    imgUrl:"images/dadjokes/dadjokes-screen.png",
    projectTitle:"DadJokesApp",
    imgFolder:"dadjokes",
    projectImagesArr:["dadjokes-screen.png","dadjokes-second.png"],
    description:"I built dadjokes app to make you a bit happier.",
    usedTecnologies:["js-icon.png","css3-icon.png","html-5.png","github-icon.png","react-icon.png","api-icon.png"]
  }

  ]
    const skillsIcon = ["api-icon.png","bootstrap-logo.png","css3-icon.png","github-icon.png","html-5.png","sass-icon.png","npm-icon.png","js-icon.png","npm-icon.png","python-icon.png","react-icon.png","webpack-icon.png","yarnpkg-icon.png","nodejs-icon.png","mongodb-icon.png","vue.js.png","postgresql-icon.png","aws-icon.png","jira-icon.png","django-icon.png"]